# Generated by Django 6.0.7 on 2026-08-03 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligne', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qrqc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_qrqc', models.IntegerField()),
                ('date_creation', models.DateField()),
                ('date_detection', models.DateField()),
                ('heure_detection', models.TimeField()),
                ('description_probleme', models.TextField()),
                ('reference_faisceau', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('securiser_ligne_zone', models.BooleanField(default=False)),
                ('informer_operateur', models.BooleanField(default=False)),
                ('poste_detection', models.CharField(max_length=50)),
                ('mode_detection', models.CharField(max_length=50)),
                ('detecte_par', models.CharField(max_length=20)),
                ('code_circuit', models.CharField(max_length=20)),
                ('famille', models.CharField(max_length=50)),
                ('qte_ok', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('qte_ng', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('escalade_niv2', models.BooleanField(default=False)),
                ('escalade_decideur', models.CharField(blank=True, max_length=50, null=True)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.ligne')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='qrqc/')),
                ('date_import', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('qrqc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.qrqc')),
            ],
        ),
        migrations.CreateModel(
            name='ContreMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('Détection', 'Détection'), ('Occurrence', 'Occurrence')], max_length=20)),
                ('cause_racine', models.TextField(blank=True, null=True)),
                ('action_corrective', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('statut_action', models.CharField(choices=[('en cours', 'En cours'), ('planifiee', 'Planifiée'), ('realisee', 'Réalisée')], default='en cours', max_length=20)),
                ('qrqc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.qrqc')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse5Pourquoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('Détection', 'Détection'), ('Occurrence', 'Occurrence')], max_length=20)),
                ('numero_pourquoi', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('qrqc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.qrqc')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviQrqc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_suivi', models.DateField()),
                ('resultat', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG')], max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('qrqc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.qrqc')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('QUALITY_ENGINEER', 'Ingénieur Qualité'), ('QUALITY_MANAGER', 'Responsable Qualité')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qrqc',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrqc.utilisateur'),
        ),
    ]
